M48
; DRILL file {KiCad 7.0.0} date Sun 12 Mar 2023 03:47:20 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-03-12T15:47:20-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X5.1181Y-3.1496
X5.1181Y-4.7244
X6.6929Y-3.1496
X6.6929Y-4.7244
T0
M30
